### ISSUE TITLE
Tarefa da trilha de HTML - Revisão

### ISSUE THREAD

**Issue by paulovictordev** [cicerohen/react-redux-saga-training#4]
Olá, gostaria que minha resolução para trilha de HTML fosse analisada, e se está de acordo com que foi proposto.

Disponibilizei o código no Codepen:  [Trilha - HTML](https://codepen.io/paulovictordev/pen/QWLoyxY)

OBS: Se entendi bem, deve está nesse formato.

**Comment by cicerohen** [comment]
Massa. Amanha dou uma olhada.

**Comment by cicerohen** [comment]
@paulovictordev  ta show. Era só esta tarefa simples mesmo, pra ir nivelando do zero, a galera.

**Comment by cicerohen** [comment]
Agora vamos subir o nível. haha

**Comment by jeanlivino** [comment]
Show, só a questão do header que eu creio que deveria estar antes do ASIDE. Tem um "spam" no aside que poderia ser um h3 e tá escrito errado.

Com um tempo você vai aprender flexbox e sair do float, mas é isso ai :D

**Comment by jeanlivino** [comment]
Pode até usar esse site para começar a praticar: https://flexboxfroggy.com/

**Comment by cicerohen** [comment]
Nas pŕoximas iremos subir um degrau no html, css e js. :D

**Comment by paulovictordev** [comment]
Blz! @cicerohen é isso ai, por simples que seja o  aprendizado é muito valido. E vamos uma etapa de cada vez.. Curti demais essa dica ai @jeanlivino , vou estudar aqui e tentar aplicar nesse exemplo. 

Muito obrigado pessoal.
