### ISSUE TITLE
Tarefa da trilha de JavaScript Básico - Revisão

### ISSUE THREAD

**Issue by paulovictordev** [cicerohen/react-redux-saga-training#5]
Olá pessoal, gostaria que minha resolução para trilha de JavaScript Básico fosse analisada, e se segue o que foi solicitado.

Disponibilizei o código no Codepen:  [Trilha - JavaScript - Básico](https://codepen.io/paulovictordev/pen/dyybbob)

Eu particularmente nunca tinha feito um modal, então fazendo algumas pesquisa pra entender o conceito por trás, consegui fazer um com o meu conhecimento. Tive algumas dificuldade principalmente com CSS, mas tentei seguir as dicas que tive na issue anterior. 

Gostaria de ter feedback sobre a estrutura HTML e na forma de usar o JS. Não tenho problema  em refatorar todo código se for preciso.

**Comment by cicerohen** [comment]
Massa. Vou revisar. :)

**Comment by brenosoares** [comment]
Olá @paulovictordev deu uma olhada aqui no que você fez e gostaria de fazer algumas observações:
Na execução do modal penso que você poderia melhorar transformando tudo em uma única função, pois vi que existe repetição demasiada na hora de chamar outros modais como você colocou, existe um código que se repete sempre.

`document.querySelectorAll('detail1');
detail1.addEventListener('click', () => startModal('modal-product'));`

Aqui você poderia deixar dentro da função segue exemplo:

`function startModal(IdModal, IdElemento, IdFechar) {
    // Determina o elemento de modal
    const modal = document.getElementById(IdModal);
    // Determina o elemento de ação para abrir modal
    const elemento = document.getElementById(IdElemento);
    // Abre Modal
    elemento.addEventListener('click', () => modal.classList.add('show'));
    // Determina o elemento de ação para fechar modal
    const elementoFechar = document.getElementById(IdFechar);
    // Fecha Modal  
    elementoFechar.addEventListener('click', () => modal.classList.remove('show'));
}

startModal('modal-product', 'detail1', 'close')
startModal('modal-product', 'detail2', 'close')
startModal('modal-product', 'detail3', 'close')`

Dessa maneira você evita ficar repetindo código e pode trabalhar com mais de um modal na mesma página. E outra coisa, como você sempre usa ID para controlar as ações, melhor usar o `document.getElementById()` em vez do `document.querySelectorAll()`.
Qualquer dúvida só falar.

**Comment by cicerohen** [comment]
@paulovictordev @brenosoares  massa, vou fazer um exemplo de código pra colocar minhas sugestões, até segunda-feira. Aí termos mais tarefas. :D

**Comment by paulovictordev** [comment]
@brenosoares saquei! Tinha tentado algo parecido mas não consegui. Usando o que vc disse eu fiz algumas alterações no código como usar apenas uma função e um parâmetro para informar se o modal deve ser aberto ou fechado. 
Tbm mudei a chamada da função para dentro do HTML, não sei se é indicado mas funciona como eu esperava. [Codigo - CodePen](https://codepen.io/paulovictordev/pen/dyybbob)

**Comment by paulovictordev** [comment]
@cicerohen , seria muito bom se em todos os desafio após um tempo, as resolução fossem apresentada. Eu já aprendi muito aqui, porem nada melhor do que comparar um código diferente que faz a mesma coisa. Novas maneiras de pensar sempre surgem.

**Comment by mensonones** [comment]
@paulovictordev, eu criei uma atividade para reactjs básico e já tenho a resolução da mesma, mas é mais enriquecedor para a galera a discussão em torno da resolução de cada um. Há diferentes maneiras de resolver  e isso que torna interessante não ter uma resolução "única".

**Comment by paulovictordev** [comment]
Exatamente @mensonones é isso que é interessante. Quando eu falo de um solução não seria uma em definitivo ou totalmente exata pelos motivos que vc falou, Mas um exemplo com uma estrutura ou um templete eu acharia valido, isso falando pro mim.
E amanhã já inicio a tarefa de reactjs, me aguarde.

**Comment by cicerohen** [comment]
@paulovictordev @brenosoares @mensonones Segue o código com minha sugestão. 
https://codepen.io/cicerohen/pen/qBBEBJN?editors=0010

@paulovictordev alguns pontos. 

**No JS**
eu usei *Revealing Module Pattern* pra encapsular as funções relativas ao modal e poder fornecer uma espécie de API, onde o mundo exterior possa interagir de forma concisa e sem se preocupar com a manipulação do DOM que ocorre no modal.

**No CSS **
eu usei o *BEM CSS* que traz a ideia de *componentização* para o CSS.

E claro, meu código é apenas um exemplo, de maneira nenhuma deve ser levado como 100% certo. Podemos comentar mais sobre ele, inclusive. :D

**Comment by paulovictordev** [comment]
@cicerohen muito bom seu exemplo. Confesso que ainda tenho que estudar muito pra chegar nesse nível de abstração. Gostei muito desse padrão utilizado no JS, demorei um pouco mais consegui sacar a ideia. Ler sobre o padrão me ajudou a entender. 

No CSS achei interessante o que o _BEM_ consegue fazer, muito melhor de ler e nomear classes.

Vou tentar aplicar no meu exemplo e disponibilizar. As duvidas que surgirem volto a contactar. Obrigado.

**Comment by cicerohen** [comment]
@paulovictordev da uma lida por cima em design patterns aplicados no js. :D

**Comment by paulovictordev** [comment]
Antes tarde do que nunca! Corrigi algumas coisas, ainda está longe do ideal mas já é uma boa evolução.

Disponibilizei o código no Codepen: [JavaScript - Básico](https://codepen.io/paulovictordev/pen/dyybbob)

**Comment by cicerohen** [comment]
> Antes tarde do que nunca! Corrigi algumas coisas, ainda está longe do ideal mas já é uma boa evolução.
> 
> Disponibilizei o código no Codepen: [JavaScript - Básico](https://codepen.io/paulovictordev/pen/dyybbob)

Massa, cara. É isso ai, JS puro é bom tbm. :D Onde tem aqueles let tu pode jogar um const de boa. :dancer:

**Comment by paulovictordev** [comment]
Blz, Corrigido! Vou encerrar a issue, dúvidas sanadas.
