### ISSUE TITLE
Revisão: Exibindo um modal usando JavaScript

### ISSUE THREAD

**Issue by andersonmadeira** [cicerohen/react-redux-saga-training#6]
Fala galera, beleza?
Alguém pode dar uma olhada e ver como poderia melhorar ou o que fariam diferente?
https://codepen.io/andersonmadeira/pen/rNNmJWm
Valeu!

**Comment by mensonones** [comment]
Curti bastante o código :) acho que não acrescentaria algo melhor, pelo menos na minha visão. O @cicerohen com seu olhar mais apurado pode talvez acrescentar algo

**Comment by cicerohen** [comment]
Opa, vou dar uma olhada. :D

**Comment by cicerohen** [comment]
Massa Anderson, achei legal, está seguindo a ideia de reusabilidade das libs JS mais antigas, antes das classes ES6. :P 

Prototype é um pattern. <3

https://addyosmani.com/resources/essentialjsdesignpatterns/book/#prototypepatternjavascript


Acho que neste caso, ao invés de:
```
ModalController.prototype = {
constructor: ModalController
```

Poderia ser feito assim:
```
ModalController.prototype.setup = function() {};
```

No MDN explica o contexto de mudança de constructor. Neste caso ai se função create está criando ele mesmo a partir do constructor, da é preciso passar o constructor(contexto) no qual a função create vai se basear.
```
function Parent() {}; 
function CreatedConstructor() {} 

CreatedConstructor.prototype = Object.create(Parent.prototype); 
CreatedConstructor.prototype.constructor = CreatedConstructor; // set right constructor for further using

CreatedConstructor.prototype.create = function create() { 
  return new this.constructor();
} 

new CreatedConstructor().create().create(); // it's pretty fine
```

**Comment by cicerohen** [comment]
@andersonmadeira no exemplo que tinha feito é uma única instância aplicando comportamento a elementos que tenham a classe correspondente. 
https://github.com/cicerohen/react-redux-saga-training/issues/5#issuecomment-540814047

**Comment by cicerohen** [comment]
function Parent() {}; 
function CreatedConstructor() {} 

CreatedConstructor.prototype = Object.create(Parent.prototype); 
//  CreatedConstructor.prototype.constructor = CreatedConstructor; 

CreatedConstructor.prototype.create = function create() { 
    return new this.constructor(); // retorna new CreatedConstructor();
}

new CreatedConstructor().create().create().create().create();

**Comment by andersonmadeira** [comment]
@cicerohen, realmente na minha implementação a linha 10
`
  constructor: ModalController,
`
Não é necessária. Vou tentar ampliar depois pra ficar mais dinâmico.
Valeu! (:

**Comment by cicerohen** [comment]
@andersonmadeira :smile:
